sulu_security:
    objects:
        user:
            model: App\Entity\User
            repository: Sulu\Bundle\SecurityBundle\Entity\UserRepository
#        role:
#            model: App\Entity\Role
#            repository: Sulu\Bundle\SecurityBundle\Entity\RoleRepository
